### ISSUE TITLE
Downspout stops downloading every day or two

### ISSUE THREAD

**Issue by justinross** [ThatOdieGuy/downspout#33]
![log](https://user-images.githubusercontent.com/1120106/37224819-69ddd876-2389-11e8-9889-30ff583e0513.jpg)
![output](https://user-images.githubusercontent.com/1120106/37224821-6a001c42-2389-11e8-8640-20a9ccfa0dc2.jpg)

**Comment by ThatOdieGuy** [comment]
Do you have any uncommitted changes? And see if you're up to date, I just pushed a minor logging fix.

I don't see any errors in the logs. There might be something funky going on with FTP. Can you enable logging for jsftp? It requires an environmental variable set prior to app launch:
`set DEBUG=jsftp*`

Then let me see the logs if this happens again. Careful, your FTP password will be logged in plain text with this logging turned on.

**Comment by ThatOdieGuy** [comment]
Fixed with #34
